#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

test ! -d build && mkdir build

common_flags='-fno-exceptions -fno-rtti -std=c++2a'
dev_flags='-g -Wall -DHHF_DEV'

libraries='-lX11'

g++ $common_flags $dev_flags \
  code/ubuntu-hhf.cpp -o build/ubuntu-hhf \
  $libraries
